# Generated by Django 3.2.10 on 2023-01-04 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaciCanvas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aim', models.CharField(max_length=255, verbose_name='Чего мы пытаемся достичь?')),
                ('if_not_reached', models.CharField(max_length=255, verbose_name='Что произойдёт, если цель не будет достигнута?')),
                ('aim_type', models.IntegerField(choices=[(1, 'Пытаемся принять решение'), (2, 'Придумать идею'), (3, 'Синхронизироваться между собой')], verbose_name='Цель')),
            ],
            options={
                'verbose_name': 'Холст фасилитации',
                'verbose_name_plural': 'Холсты фасилитации',
                'db_table': 'app_faci_canvas',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Участник встречи',
                'verbose_name_plural': 'Участники встречи',
                'db_table': 'app_faci_member',
            },
        ),
    ]
