# Generated by Django 3.2.10 on 2023-01-04 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faci', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facicanvas',
            name='aim_type',
            field=models.IntegerField(choices=[(1, 'Принять решение'), (2, 'Придумать идею'), (3, 'Синхронизироваться между собой')], verbose_name='Вид встречи'),
        ),
    ]
