# Generated by Django 3.2.10 on 2023-01-07 14:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('faci', '0002_alter_facicanvas_aim_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='facicanvas',
            name='dt_create',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 7, 14, 31, 14, 677247)),
        ),
        migrations.AddField(
            model_name='facicanvas',
            name='dt_modify',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 7, 14, 31, 14, 677410)),
        ),
        migrations.AddField(
            model_name='facicanvas',
            name='user_creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='facicanvas',
            name='aim',
            field=models.CharField(max_length=255, verbose_name='Что мы пытаемся достичь?'),
        ),
    ]
