# Generated by Django 3.2.10 on 2023-01-07 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faci', '0004_auto_20230107_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='facicanvas',
            name='dt_meeting',
            field=models.DateTimeField(null=True, verbose_name='Дата и время'),
        ),
    ]
