# Generated by Django 3.2.10 on 2023-01-07 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faci', '0005_facicanvas_dt_meeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='facicanvas',
            name='duration',
            field=models.IntegerField(default=30, verbose_name='Длительность'),
        ),
        migrations.AddField(
            model_name='facicanvas',
            name='place',
            field=models.CharField(default='', max_length=100, verbose_name='Место'),
        ),
    ]
