# Generated by Django 3.2.10 on 2023-01-11 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faci', '0007_auto_20230107_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facicanvas',
            name='key_thoughts',
            field=models.TextField(blank=True, default='', max_length=10000, verbose_name='Ключевые мысли'),
        ),
        migrations.AlterField(
            model_name='facicanvas',
            name='parked_thoughts',
            field=models.TextField(blank=True, default='', max_length=10000, verbose_name='Парковка'),
        ),
        migrations.AlterField(
            model_name='facicanvas',
            name='place',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Место'),
        ),
    ]
