# Generated by Django 3.2.10 on 2023-01-15 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faci', '0008_auto_20230111_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facicanvas',
            name='aim_type',
            field=models.IntegerField(choices=[(1, 'Принять решение'), (2, 'Придумать идею'), (3, 'Синхронизироваться между собой'), (4, 'Прочее')], default=1, verbose_name='Вид встречи'),
        ),
        migrations.AlterField(
            model_name='facicanvas',
            name='duration',
            field=models.IntegerField(default=30, verbose_name='Длительность, минуты'),
        ),
    ]
