# Generated by Django 3.2.10 on 2023-01-16 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faci', '0009_auto_20230115_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='facicanvas',
            name='step',
            field=models.IntegerField(default=1, verbose_name='Шаг'),
        ),
    ]
