# Generated by Django 3.2.10 on 2023-01-22 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faci', '0010_facicanvas_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='facicanvas',
            name='is_deleted',
            field=models.IntegerField(default=0, verbose_name='Холст удалён'),
        ),
    ]
