# Generated by Django 3.2.10 on 2023-01-22 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faci', '0011_facicanvas_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facicanvas',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='facicanvas',
            name='is_closed',
            field=models.IntegerField(default=0, verbose_name='Холст закрыт'),
        ),
    ]
