# Generated by Django 3.2.10 on 2023-01-22 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('faci', '0012_auto_20230122_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='faci_canvas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faci.facicanvas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='for_what',
            field=models.CharField(max_length=200, verbose_name='В каком вопросе компетентен'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='invited',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faci_members', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='inviting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faci_member_inviters', to='auth.user'),
            preserve_default=False,
        ),
    ]
