# Generated by Django 3.2.10 on 2023-02-04 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faci', '0013_auto_20230122_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='questions',
            field=models.CharField(blank=True, default='', max_length=2000, verbose_name='Мнения и вопросы'),
        ),
        migrations.AddField(
            model_name='member',
            name='themes',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='Предлагаемые темы'),
        ),
        migrations.AddField(
            model_name='member',
            name='themes_duration',
            field=models.IntegerField(default=5, verbose_name='Длительность выступления, минуты'),
        ),
        migrations.AlterField(
            model_name='facicanvas',
            name='duration',
            field=models.IntegerField(default=30, verbose_name='Длительность встречи, минуты'),
        ),
    ]
