# Generated by Django 3.2.10 on 2023-02-08 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faci', '0015_facicanvas_meeting_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='facicanvas',
            name='other_agreements',
            field=models.TextField(blank=True, default='', max_length=10000, verbose_name='Прочие договорённости'),
        ),
    ]
