# Generated by Django 3.2.10 on 2023-02-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faci', '0016_facicanvas_other_agreements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facicanvas',
            name='duration',
            field=models.IntegerField(default=30, verbose_name='Длительность'),
        ),
    ]
