# Generated by Django 3.2.10 on 2023-01-12 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='externgoogleuser',
            name='is_username_changed',
            field=models.BooleanField(default=False),
        ),
    ]
