# Generated by Django 3.2.10 on 2023-01-13 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('custom_auth', '0002_externgoogleuser_is_username_changed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=20, verbose_name='Наименование приложения')),
                ('token', models.CharField(max_length=100, unique=True, verbose_name='Токен для доступа к API сервера')),
                ('expire_dt', models.DateTimeField(verbose_name='Время жизни токена')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Токен',
                'verbose_name_plural': 'Токены',
                'db_table': 'app_custom_auth_token',
            },
        ),
    ]
