# Generated by Django 3.2.10 on 2023-01-15 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0003_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='expire_dt',
            field=models.DateTimeField(null=True, verbose_name='Время жизни токена'),
        ),
    ]
