# Generated by Django 3.2.10 on 2023-02-19 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0004_alter_token_expire_dt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externgoogleuser',
            name='extern_id',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(max_length=128, unique=True, verbose_name='Токен для доступа к API сервера'),
        ),
    ]
